# Generated by Django 3.0.2 on 2020-02-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='puntInteres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('logitud', models.FloatField()),
                ('idMapa', models.IntegerField()),
                ('tipus', models.CharField(max_length=700)),
                ('actiu', models.BooleanField()),
                ('superficie', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='usuari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('cognom', models.CharField(max_length=500)),
                ('contrassenya', models.CharField(max_length=500)),
                ('correuElectronic', models.EmailField(max_length=254)),
                ('superUsuari', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomLocal', models.CharField(max_length=500)),
                ('puntuacio', models.IntegerField()),
                ('categoria', models.CharField(max_length=200)),
                ('localitzacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeoInfoSystem.puntInteres')),
            ],
        ),
    ]
