# Generated by Django 3.0.2 on 2020-02-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInfoSystem', '0002_local_anyconstruccio'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='descripcio',
            field=models.CharField(default='', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puntinteres',
            name='localitat',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
