# Generated by Django 3.0.2 on 2020-02-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInfoSystem', '0003_auto_20200202_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntinteres',
            name='pais',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
