# Generated by Django 3.0.2 on 2020-02-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInfoSystem', '0005_auto_20200203_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='idLocal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puntinteres',
            name='idPuntInteres',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
