# Generated by Django 3.0.2 on 2020-02-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInfoSystem', '0007_usuari_alies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuari',
        ),
    ]
