# Generated by Django 3.0.2 on 2020-02-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInfoSystem', '0008_delete_usuari'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='local',
            name='idLocal',
        ),
        migrations.RemoveField(
            model_name='puntinteres',
            name='idPuntInteres',
        ),
    ]
