# Generated by Django 3.0.2 on 2020-03-20 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInfoSystem', '0009_auto_20200214_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='localitzacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciutat', models.CharField(max_length=150)),
                ('comarca', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='local',
            old_name='puntuacio',
            new_name='estat_conservacio',
        ),
        migrations.RemoveField(
            model_name='puntinteres',
            name='idMapa',
        ),
        migrations.RemoveField(
            model_name='puntinteres',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='puntinteres',
            name='tipus',
        ),
        migrations.AlterField(
            model_name='local',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeoInfoSystem.categoriaLocal'),
        ),
        migrations.AlterField(
            model_name='puntinteres',
            name='localitat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeoInfoSystem.localitzacio'),
        ),
    ]
