# Generated by Django 3.0.2 on 2020-04-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInfoSystem', '0012_imatgelocal'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='imatge',
            field=models.ImageField(default=None, upload_to='photo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='imatgeLocal',
        ),
    ]
