# Generated by Django 3.0.2 on 2020-04-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInfoSystem', '0014_auto_20200422_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='imatges_taula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imatge_locals', models.BinaryField(blank=True)),
            ],
        ),
    ]
