# Generated by Django 3.0.2 on 2020-04-24 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInfoSystem', '0015_imatges_taula'),
    ]

    operations = [
        migrations.CreateModel(
            name='imatges_locals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imatge', models.BinaryField(blank=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeoInfoSystem.local')),
            ],
        ),
        migrations.RemoveField(
            model_name='imagelocal',
            name='local',
        ),
        migrations.DeleteModel(
            name='imatges_taula',
        ),
        migrations.DeleteModel(
            name='imageLocal',
        ),
    ]
