# Generated by Django 3.0.2 on 2020-05-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInfoSystem', '0017_imagelocal'),
    ]

    operations = [
        migrations.CreateModel(
            name='paraulesClauGIS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paraula', models.CharField(max_length=600)),
                ('idioma', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='imatges_locals',
        ),
    ]
